name: Simphonea Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4

      - name: Create Simphonea Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Simphonea-Web-App
          path: |
            DISEÑO.HTML
            manifest.json
            .github/workflows/main.yml